name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: docker login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_USER_PASSWORD }}
    - name: docker image create
      run: docker run -d --name ccflow --privileged ryolong1988/ubuntu-laravel:0.04 /sbin/init
    - name: docker src copy
      run: docker cp /home/runner/work/github-actions-demo/github-actions-demo ccflow:/var
    - name: docker commit
      run: docker commit ccflow ryolong1988/ubuntu-laravel:0.05
    - name: docker push
      run: docker push ryolong1988/ubuntu-laravel:0.05
